/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author Oscar
 */
public class PnlTextEditor extends javax.swing.JPanel {

    /**
     * Creates new form PnlTextEditor
     */
    public PnlTextEditor() {
        initComponents();
    }

    public JScrollPane getPanelTextEditor() {
        return PanelTextEditor;
    }

    public void setPanelTextEditor(JScrollPane PanelTextEditor) {
        this.PanelTextEditor = PanelTextEditor;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JLabel getLblLetters() {
        return lblLetters;
    }

    public void setLblLetters(JLabel lblLetters) {
        this.lblLetters = lblLetters;
    }

    public JLabel getLblLines() {
        return lblLines;
    }

    public void setLblLines(JLabel lblLines) {
        this.lblLines = lblLines;
    }

    public JLabel getLblWords() {
        return lblWords;
    }

    public void setLblWords(JLabel lblWords) {
        this.lblWords = lblWords;
    }

    public JTextPane getTextPanel() {
        return textPanel;
    }

    public void setTextPanel(JTextPane textPanel) {
        this.textPanel = textPanel;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLines = new javax.swing.JLabel();
        lblLetters = new javax.swing.JLabel();
        lblWords = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        PanelTextEditor = new javax.swing.JScrollPane();
        textPanel = new javax.swing.JTextPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lblLines.setText("Lines:");
        jPanel1.add(lblLines);

        lblLetters.setText("Letters:");
        jPanel1.add(lblLetters);

        lblWords.setText("Words:");
        jPanel1.add(lblWords);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        PanelTextEditor.setViewportView(textPanel);

        jPanel2.add(PanelTextEditor, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PanelTextEditor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLetters;
    private javax.swing.JLabel lblLines;
    private javax.swing.JLabel lblWords;
    private javax.swing.JTextPane textPanel;
    // End of variables declaration//GEN-END:variables
}
